export const LOCATION_ATTEMPT = "LOCATION_ATTEMPT";
export const ADD_DESTINATION = "ADD_DESTINATION";
export const UPDATE_CURRENT_POSITION = "UPDATE_CURRENT_POSITION";
export const ADD_NON_CONVERTED_LOCATION = "ADD_NON_CONVERTED_LOCATION";
